export enum EmployeeReportStatus {
    Present = 1,
    NoSignIn = 2,
    NoSignOut = 3,
    ExemptionIn = 4,
    ExemptionOut = 5,
    ExemptionInOut = 6,
    EmergencyAllowance = 7,
    Vacation = 8,
    Weekend = 9,
    RestDay = 10,
    Absence = 11,
    Late = 12,
    Holiday = 13,
    FullDayPermission = 14,
    Permission = 15,
    Overtime = 16,
    DutyNotStart = 17,
    ThrowDuty = 18,
    AllowanceIn = 19,
    AllowanceOut = 20,
    AllowanceInOut = 21,
    BreakNoSign = 22,
}
